### ISSUE TITLE
HostedOn column

### ISSUE THREAD

**Issue by smurton** [sacha81/XA-and-XD-HealthCheck#18]
the HostedOn column is not working with the latest version, The report no longer displays which VMware host the server or desktop is running on.

**Comment by smurton** [comment]
after reviewing further it looks like a typo...I looked through the script and noted the 2 differences. 

HostetOn
HostedOn

**Comment by tyron** [comment]
Thanks for noting. Probably got overwritten when I pushed a new version (git newbie).
I pulled a correction now (#21), should be approved soon.
