### ISSUE TITLE
Add Citrix Studio Power State status

### ISSUE THREAD

**Issue by ryanchauvin** [sacha81/XA-and-XD-HealthCheck#2]
Sacha,
Can you add a column to give the Citrix Studio Power State status of each XenApp/XenDesktop? I ran into an issue this week that Studio was pulling an UNKNOWN Power State and would not let users login to them. This fix was to reboot one of my Delivery Controllers, but didn’t see the UNKNOWN Power State until I connected with Citrix Studio.

**Comment by sacha81** [comment]
Sovled in 0.99 for Desktops, for powered off Desktops no further checks will be done.
