### ISSUE TITLE
Incorrect "DesktopsFree"

### ISSUE THREAD

**Issue by tyron** [sacha81/XA-and-XD-HealthCheck#22]
I am not sure what is the difference of columns "DesktopsAvailable" and "DesktopsFree" in the XenDesktop table. Can you clarify @sacha81 please?

According to [documentation](https://docs.citrix.com/en-us/xenapp-and-xendesktop/7-6/cds-sdk-wrapper-rho/xad-commands/citrix-broker-admin-v2-wrapper-xd76/get-brokerdesktopgroup-xd76.html), the DesktopsAvailable should already disregard sessions in use. Thus, I believe that the DesktopsFree column is not necessary.

**Comment by sacha81** [comment]
If you have e.g. 50 pooled VDIs and there are 14 in use, you can see that you have 36 Free desktops. Guess this feature is only relevant for pooled desktops.
