### ISSUE TITLE
Doesn't show accurate maintenance mode details

### ISSUE THREAD

**Issue by crypticedge** [sacha81/XA-and-XD-HealthCheck#29]
I placed a test server in to maintenance mode and ran the script to try to get it to trigger a failure on that, and it shows it's still out of maintenance mode. One of the key things we want this script for is identifying servers we forgot to bring back out of it. 

Both Studio and Director correctly reflect the maintenance mode setting accurately. 

![image](https://cloud.githubusercontent.com/assets/2439824/20396039/e1c807c0-acb2-11e6-8975-34cf65dffeaa.png)

We're also seeing a lot of errors 

The variable '$EnvironmentName' cannot be retrieved because it has not been set.
At C:\scripts\XA-and-XD-HealthCheck.ps1:1235 char:21
+ $EnvironmentName = "$EnvironmentName $XDVersion"
+                     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (EnvironmentName:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

New-Variable : Cannot overwrite variable EnvironmentName because the variable has been optimized. Try using the
New-Variable or Set-Variable cmdlet (without any aliases), or dot-source the command that you are using to set the
variable.
At C:\scripts\XA-and-XD-HealthCheck.ps1:74 char:26
+         If ($CreateVariable) { New-Variable -Name $_.Name -Value $VarValue -Scope $_.S ...
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (EnvironmentName:String) [New-Variable], SessionStateUnauthorizedAccessExcep
   tion
    + FullyQualifiedErrorId : VariableNotWritableRare,Microsoft.PowerShell.Commands.NewVariableCommand

New-Variable : Cannot overwrite variable ShowXenAppTable because the variable has been optimized. Try using the
New-Variable or Set-Variable cmdlet (without any aliases), or dot-source the command that you are using to set the
variable.
At C:\scripts\XA-and-XD-HealthCheck.ps1:74 char:26
+         If ($CreateVariable) { New-Variable -Name $_.Name -Value $VarValue -Scope $_.S ...
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (ShowXenAppTable:String) [New-Variable], SessionStateUnauthorizedAccessExcep
   tion
    + FullyQualifiedErrorId : VariableNotWritableRare,Microsoft.PowerShell.Commands.NewVariableCommand

New-Variable : Cannot overwrite variable PvsWriteMaxSize because the variable has been optimized. Try using the
New-Variable or Set-Variable cmdlet (without any aliases), or dot-source the command that you are using to set the
variable.
At C:\scripts\XA-and-XD-HealthCheck.ps1:74 char:26
+         If ($CreateVariable) { New-Variable -Name $_.Name -Value $VarValue -Scope $_.S ...
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (PvsWriteMaxSize:String) [New-Variable], SessionStateUnauthorizedAccessExcep
   tion
    + FullyQualifiedErrorId : VariableNotWritableRare,Microsoft.PowerShell.Commands.NewVariableCommand

The variable '$PvsWriteMaxSize' cannot be retrieved because it has not been set.
At C:\scripts\XA-and-XD-HealthCheck.ps1:81 char:20
+ $PvsWriteMaxSize = $PvsWriteMaxSize * 1Gb
+                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PvsWriteMaxSize:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

**Comment by sacha81** [comment]
We know there are still a few errors. But when you set a Server in maint you should not check the delivery group for maint, see in the server section to see server in maint. Your picture shows delivery grous.

**Comment by crypticedge** [comment]
That's great and all, but reading the XML I'm not seeing anywhere to edit in machine names, nor does it populate them from it's checks against the delivery controller.

**Comment by sacha81** [comment]
it should check all maschines - output should be like that: blog.sachathomet.ch/wp-content/uploads/xdxa-hc-09.jpg

**Comment by crypticedge** [comment]
And that's why I have a problem, it does not check them. 
Here is the full output it returns
![image](https://cloud.githubusercontent.com/assets/2439824/20397526/06d22a28-acb8-11e6-86ed-d89b81868ca8.png)

**Comment by sacha81** [comment]
whats in the log file?

**Comment by crypticedge** [comment]
#### Begin with Citrix XenDestop / XenApp HealthCheck ######################################################################
 
PSSnapIn: Citrix.Broker.Admin.V2
Check Controllers #############################################################################
 
Version: 7.11.0.23 
XenDesktop/XenApp Version above 7.x (7.11.0.23) - XenApp and DesktopCheck will be performed
Controller: <redacted>
State: Active
Registered: 13
ActiveSiteServices ControllerReaper ControllerNameCacheRefresh Licensing BrokerReaper RegistrationHardening WorkerNameCacheRefresh AccountNameCacheRefresh PowerPolicy GroupUsage AddressNameResolver RebootScheduleManager RebootCycleManager ScopeNamesRefresh FeatureChecks RemotePC IdleSessionManager LeaseReaper OperationalEventsService CIOCloud
CPU usage is normal [ 1.7 % ]
Memory usage is normal [ 66.9 % ]
[WARNING] Disk Free is Low [ 13.43 % ]
[ERROR] Error returned while checking the Hard Disk usage. Perfmon Counters may be fault
[WARNING] reboot warning, last reboot: Thursday, November 17, 2016
 --- 
Check Catalog #################################################################################

Catalog: ...
Excluded Catalog, skipping
 --- 
Catalog: ...
Assigned: 0
Unassigned: 1
Used: 1
ProvisioningType: Manual
AllocationType: Random
 --- 
Catalog: ...
Assigned: 0
Unassigned: 2
Used: 2
ProvisioningType: Manual
AllocationType: Random
 --- 
Catalog: ...
Assigned: 0
Unassigned: 1
Used: 1
ProvisioningType: Manual
AllocationType: Random
 --- 
Catalog: ...
Assigned: 0
Unassigned: 1
Used: 1
ProvisioningType: Manual
AllocationType: Random
 --- 
Catalog: ... Demo
Assigned: 0
Unassigned: 1
Used: 1
ProvisioningType: Manual
AllocationType: Random
 --- 
Catalog: ...
Assigned: 0
Unassigned: 1
Used: 1
ProvisioningType: Manual
AllocationType: Random
 --- 
Catalog: ...
Assigned: 0
Unassigned: 1
Used: 1
ProvisioningType: Manual
AllocationType: Random
 --- 
Catalog: ...
Assigned: 0
Unassigned: 2
Used: 2
ProvisioningType: Manual
AllocationType: Random
 --- 
Check Assigments #############################################################################
 
DeliveryGroup: ...
Excluded Delivery Group, skipping
 --- 
DeliveryGroup: ...
PublishedName: ...
DesktopsAvailable: 1
DesktopsAvailable: 0
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 1
DesktopsFree: -1
DesktopsFree < 1 ! (-1)
 --- 
DeliveryGroup: ...
PublishedName: ...
DesktopsAvailable: 2
DesktopsAvailable: 0
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 2
DesktopsFree: -2
DesktopsFree < 1 ! (-2)
 --- 
DeliveryGroup: ...
PublishedName: ...
DesktopsAvailable: 1
DesktopsAvailable: 0
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 1
DesktopsFree: -1
DesktopsFree < 1 ! (-1)
 --- 
DeliveryGroup: ...
PublishedName: ...
DesktopsAvailable: 1
DesktopsAvailable: 0
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 1
DesktopsFree: -1
DesktopsFree < 1 ! (-1)
 --- 
DeliveryGroup: ... Demo
PublishedName: ... Demo
DesktopsAvailable: 1
DesktopsAvailable: 1
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 0
DesktopsFree: 1
DesktopsFree < 1 ! (1)
 --- 
DeliveryGroup: ...
PublishedName: ...
DesktopsAvailable: 1
DesktopsAvailable: 0
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 1
DesktopsFree: -1
DesktopsFree < 1 ! (-1)
 --- 
DeliveryGroup: ...
PublishedName: ...
DesktopsAvailable: 1
DesktopsAvailable: 0
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 1
DesktopsFree: -1
DesktopsFree < 1 ! (-1)
 --- 
DeliveryGroup: ...
PublishedName: ...
DesktopsAvailable: 2
DesktopsAvailable: 0
DesktopKind: Shared
inMaintenanceMode: False
DesktopsUnregistered: 0
DesktopsUnregistered <= 0 ! (0)
DesktopsInUse: 2
DesktopsFree: -2
DesktopsFree < 1 ! (-2)
 --- 

Check virtual Desktops ####################################################################################
 
Check XenApp Servers ####################################################################################
 
####################### Check END ####################################################################################

**Comment by crypticedge** [comment]
Got it figured out. 

I had to add a $ShowXenAppTable = 1 between line 499 and 500. Now it's populating properly.

**Comment by crypticedge** [comment]
Oh, I also changed the Add-PSSnapin to citrix* but I don't think that was the fix. Pretty sure adding the variable in at that line fixed it.

**Comment by sacha81** [comment]
You don't have to change it in the Script, just set it in the XML:

	<Name>ShowXenAppTable</Name>
			<Value>1</Value>
			<Type>[int]</Type>
		<Scope>Script</Scope>

To change the SnappIn to citrix* will give you more overhead.

**Comment by crypticedge** [comment]
I have that set in the xml, it did not use that field at all when it ran, still throwing an error that it was not set

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Nov 18, 2016 at 3:13 AM -0500, "Sacha Thomet" <notifications@github.com<mailto:notifications@github.com>> wrote:


You don't have to change it in the Script, just set it in the XML:

<Name>ShowXenAppTable</Name>
        <Value>1</Value>
        <Type>[int]</Type>
    <Scope>Script</Scope>


To change the SnappIn to citrix* will give you more overhead.

-
