### ISSUE TITLE
1.2.3 and 1.2.4 Script doesn't run properly with a scheduled task

### ISSUE THREAD

**Issue by ryanchauvin** [sacha81/XA-and-XD-HealthCheck#31]
I can confirm that both 1.2.3 and 1.2.4 DOES NOT run correctly with a Scheduled Task. My signature in the email isn’t correct, nor the body of the email. It is missing all the target device information. If I open it up in PowerShell ISE and hit the play button everything works as expected. Again, this stopped working in both 1.2.3 and 1.2.4.

1.2.3 works just fine.

**Comment by sacha81** [comment]
the user who runs the scheduled task has no interactive logon permission. You can fix that when you start the script with the parameter -NonInteractive 
e.g.
powershell.exe -NonInteractive -file C:\task\XA-and-XD-HealthCheck.ps1
