### ISSUE TITLE
Exclude Servers/Desktop by a specific tag in Studio 

### ISSUE THREAD

**Issue by sacha81** [sacha81/XA-and-XD-HealthCheck#33]
e.g. if a Machine has the tag "noHealthCheck" it will be exluded in the HealthCheck

**Comment by mikekacz** [comment]
Proposed in Pull request #37

**Comment by sacha81** [comment]
mikekacz proposed in Pull request #37

**Comment by rajneeshsaraswat** [comment]
did we get any update on this.

**Comment by sacha81** [comment]
no, because it's implemented this issue is closed.
