### ISSUE TITLE
Error during License Check with XA 7.6 LTSR

### ISSUE THREAD

**Issue by tinex81** [sacha81/XA-and-XD-HealthCheck#44]
Hi sacha81 ,
great script , i used it on several customer.

However i dowloaded the lastest version and when i run the script on a delivery controller , farm XA 7.6 LTSR , and from an elevated powershell command , i get the following error.
In the same folder there is the parameter file compiled with my enviroment.

> PS C:\Users\tinex\Downloads\Check> .\XA-and-XD-HealthCheck.ps1 .\XA-and-XD-HealthCheck_Parameters.xml
> You must provide a value expression on the right-hand side of the '-' operator.
> At C:\Users\tinex\Downloads\Check\XA-and-XD-HealthCheck.ps1:812 char:167
> +         $LicWMIQuery = get-wmiobject -namespace "ROOT\CitrixLicensing" -computer $lsname -query "select * from Citrix
> _GT_License_Pool" -ErrorAction Stop | ? {$_.PLD - <<<< in $CTXLicenseMode}
>     + CategoryInfo          : ParserError: (:) [], ParseException
>     + FullyQualifiedErrorId : ExpectedValueExpression

**Comment by mikekacz** [comment]
Please try starting that in Powershell 3.0.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Pozdrawiam
Michał Kaczmarek

**Comment by sacha81** [comment]
please try with script 1.3.9.1 - fixed the license reading
