### ISSUE TITLE
Display error XenApp Memory consumption 

### ISSUE THREAD

**Issue by sacha81** [sacha81/XA-and-XD-HealthCheck#5]
Memory between 8.5% an 10% is red and between 7.5 and 8.5 yellow instead of green.

**Comment by grizzljt** [comment]
Adding [INT] to the variable fixes it, like so:
[int]$XAAvgCPUval = CheckCpuUsage ($machineDNS)

**Comment by sacha81** [comment]
Solved with the code of grizzljt in Version 0.98
