### ISSUE TITLE
Excluded Catalogs should be not processed 

### ISSUE THREAD

**Issue by sacha81** [sacha81/XA-and-XD-HealthCheck#56]
Excluded Catalogs should not only be skipped in the report instead it should not be processed to avoid wasting execution time. (Thanks for the input Saravana)

**Comment by piyushks86** [comment]
Hi Sacha,

Can we exclude a particular delivery group and all servers in that delivery group from the report?

Regards
Piyush

**Comment by piyushks86** [comment]
I am using version 1.2.2 

Regards
Piyush

**Comment by sacha81** [comment]
the current version is 1.3.4, but this don't have the function for a DeliveryGroup, just for Catalogs (Line 42-48 in XA-and-XD-HealthCheck_Parameters.xml ) 

Or you can work with tags (Line 49-55 in XA-and-XD-HealthCheck_Parameters.xml ) 

Both just excludes in the Report, but is needs anyway time for the check. Hope I have some day time to improve this.

**Comment by ImSaravana77** [comment]
Hi Sacha, 

Thanks for looking into this. Today had some time and tried with below snippet and it's working fine. If you are okay with that mean, I can merge it with the PowerShell script.

if ((Get-PSSnapin "Citrix.Broker.Admin.*" -EA silentlycontinue) -eq $null) {
try { Add-PSSnapin Citrix.Broker.Admin.* -ErrorAction Stop }
catch { write-error "Error Get-PSSnapin Citrix.Broker.Admin.* Powershell snapin"; Return }
}
$AdminAddress = "localhost"
$maxmachines=500
clear
$CatalogResults = @{}
$Catalogs = Get-BrokerCatalog -AdminAddress $AdminAddress
$ExcludedCatalogs='MachineCatalog1','Machinecatalog2'
foreach ($Catalog in $Catalogs) {
  $tests = @{}
  
  #Name of MachineCatalog
  $CatalogName = $Catalog | %{ $_.Name }

   if ($ExcludedCatalogs -contains $CatalogName ) 
  { 
  "$machineDNS in excluded folder in $CatalogName - skipping" 
  }
else 
{
  $XAmachines = Get-BrokerMachine -MaxRecordCount $maxmachines -MachineName "*" -CatalogName $CatalogName -AdminAddress $AdminAddress #| Where-Object {$_.SessionSupport -eq "MultiSession" -and @(compare $_.tags $ExcludedTags -IncludeEqual | ? {$_.sideindicator -eq '=='}).count -eq 0}
  foreach ($XAmachine in $XAmachines) {
$tests = @{}
 
  # Column Name of Machine
$machineDNS = $XAmachine | %{ $_.DNSName }
Write-Host "Server $machineDNS in $CatalogName" #$XAmachine
}
  }

  }

**Comment by ImSaravana77** [comment]
Hi Sacha, 

Attached script is working fine and it is not processing the excluded catalog, however, need to check the excluded tag and catalog name. can you please check the line 1238, needs to correct it for tagging. can you please check the syntax.

I commented my changes in #skip (line: 1218-1246)

[XA-and-XD-HealthCheck_exclude.txt](https://github.com/sacha81/XA-and-XD-HealthCheck/files/1949828/XA-and-XD-HealthCheck_exclude.txt)

**Comment by sacha81** [comment]
something is wrong in the script, I only see **one** XenApp catalog when I run your version

**Comment by Im-Saravana** [comment]
Ah! I will do the test again.

**Comment by Im-Saravana** [comment]
just moved the line #1236 and #1223 to 1220, Issue reolved,. Problem was with the data set resetting inside the loop ($allXenAppResults = @{}) so last catalog server checks onlu saving in the result.

Attached the corrected script. Also on line 1238 if you are making changes on adding Catalog name verification or tagging would be fix the tag exclusions. I scripting language is not good enough to work on that line.
[XA-and-XD-HealthCheck_exclude.txt](https://github.com/sacha81/XA-and-XD-HealthCheck/files/1959491/XA-and-XD-HealthCheck_exclude.txt)

**Comment by sacha81** [comment]
there is still something wrong - now I have an empty catalogs table. sorry that I currently have more time to support on this.

**Comment by sacha81** [comment]
I just tested successfully and merged into the master branch - tagging work now. Please test now again against your environment.

**Comment by mikekacz** [comment]
Hi, long time. 
This can be fixed like this.

in every line that populates _$machines_ like:
`$machines = Get-BrokerMachine -MaxRecordCount $maxmachines -AdminAddress $AdminAddress| Where-Object ...`

add additional condition:
`-and $_.catalogname -notin $ExcludedCatalogs`

and side note line 980 will not work, _Get-BrokerMachine_ does not have _-and_ parameter.

**Comment by sacha81** [comment]
fixed with version 1.4.6
