### ISSUE TITLE
Output file for License & Catalog does not populate

### ISSUE THREAD

**Issue by ramtamilan** [sacha81/XA-and-XD-HealthCheck#57]
Hi ,
I have tried running the script. But I have couple of issue with License & Catalog information on output HTML. On output HTML file, for License - I get Licenseserver name but other details show as N/A. My second issue is Cataloginformation returns blank, though log file has the information. It only shows the table header. I have attached screenshot for reference. Any assistance on this will be much appreciated
![error](https://user-images.githubusercontent.com/12909170/42738988-0d3c8798-887e-11e8-877d-728cd67824c2.JPG)

**Comment by sacha81** [comment]
does that work:

get-wmiobject -namespace "ROOT\CitrixLicensing" -computer YOURSERVER -query "select * from Citrix_GT_License_Pool"

If not you first you need to get that working ...

**Comment by sacha81** [comment]
just the licensing stuff or all? If all check permission and logfile.

**Comment by iaakashthakkar** [comment]
only catalog details not populating. while running the script i can see machine catalog details are fetched but not populating in HTML file
<img width="696" alt="catalog" src="https://user-images.githubusercontent.com/43161832/45339997-71a14280-b5b2-11e8-922c-c9f982a78ff2.PNG">
