### ISSUE TITLE
Add Trust Relationship Check

### ISSUE THREAD

**Issue by sommerers** [sacha81/XA-and-XD-HealthCheck#6]
I wanted to see if you could add something to your script that would test the Trust Relationship of the VDA's. 

My initial thoughts are that you could try to pull the first event log from the VDA if it fails it could indicate that there is a Trust Relationship issue.

**Comment by sacha81** [comment]
If there is no domain trust you are not able to check e number of items (memory, cpu, etc.) - so you will notice that you have a problem.

**Comment by sommerers** [comment]
Good point

**Comment by sacha81** [comment]
Hope it's ok when I close this feature request for the moment.
