### ISSUE TITLE
Catalog does not populate 

### ISSUE THREAD

**Issue by iaakashthakkar** [sacha81/XA-and-XD-HealthCheck#61]
Catalog data not populating in html file.

**Comment by sacha81** [comment]
this is not a general error, it does on several environments and on all I know. So I can't troubleshoot on that.

**Comment by MikedaSpike** [comment]
Isn't this caused by line 1256 ?
The array $CatalogResults is set to empty again, after it is being fileld.
When I commented this out it is working

**Comment by sacha81** [comment]
solved in v 1.4.1
