### ISSUE TITLE
added column "LastConnect" to table of desktops

### ISSUE THREAD

**Issue by loefflerman** [sacha81/XA-and-XD-HealthCheck#62]
Hi Sacha, i like your report-script very much and to make it more handy for us I allowed to add a column to the desktop-table which shows the last connection date and colors it yellow or red if its older than 1 or two months.
We try to identify desktops that have not been used for a longer time.

Maybe someone is interested to get my code-snippets or you want to insert it into your code ?

Regards, Markus

**Comment by sacha81** [comment]
I really like this feature! Nice idea! Love to add it to my code. You can add it to my code directly within here.

**Comment by loefflerman** [comment]
I added my code using the "Create new file" feature. I am not sure if thats the correct way?

**Comment by sacha81** [comment]
no, think you need to clone and then commit, but you can send me the new file to sacha.thomet (at gmail.com and i will add the new code.

**Comment by sacha81** [comment]
Thanks, 1.37 is now on Github
