### ISSUE TITLE
script collecting catalog data but not updating on HTML

### ISSUE THREAD

**Issue by tamilbabuece** [sacha81/XA-and-XD-HealthCheck#64]
script collecting catalog data but not updating on HTML

**Comment by sacha81** [comment]
Not a general issue, permission on file? Or just issue with catalog data and all other is updating?

**Comment by MikedaSpike** [comment]
Isn't this caused by line 1256 ?
The array $CatalogResults is set to empty again, after it is being fileld.
When I commented this out it is working

**Comment by tamilbabuece** [comment]
> Isn't this caused by line 1256 ?
> The array $CatalogResults is set to empty again, after it is being filled with values
> When I commented this out it is working

Thank u very much MikedaSpike for finding the issue.
After Commented the line script working fine
