### ISSUE TITLE
Script hung on server that has  WMI error

### ISSUE THREAD

**Issue by MikedaSpike** [sacha81/XA-and-XD-HealthCheck#65]
In our environment, we noticed that sometimes a server doesn't pass the $WMI. When this happend the performance counters for WMI is hung when retrieving this.

I added as a quick and dirty method the variable $WMItest : 
```
$wmi = Wait-job $job -Timeout 15 | Receive-Job
  $WmiTest = $False
  # Perform WMI related checks
  if ($wmi -ne $null) {
    $tests.WMI = "SUCCESS", "Success"
    $WmiTest = $True
    $LBTime=[Management.ManagementDateTimeConverter]::ToDateTime($wmi.Lastbootuptime)
    [TimeSpan]$uptime=New-TimeSpan $LBTime $(get-date)
  
    if ($uptime.days -gt $maxUpTimeDays) {
      "reboot warning, last reboot: {0:D}" -f $LBTime | LogMe -display -warning
      $tests.Uptime = "WARNING", $uptime.days
      $ErrorVDI = $ErrorVDI + 1
    } else { 
      $tests.Uptime = "SUCCESS", $uptime.days 
    }
  } else { 
    "WMI connection failed - check WMI for corruption" | LogMe -display -error
    stop-job $job
  }
```
With this variable ($WMItest) I will skipp or allow the WMI checks
For memory check and HD check(thats using WMI) , I changed to the following :

```        # Check the Physical Memory usage
        if ($WmiTest -eq $True) {
            [int] $XAUsedMemory = CheckMemoryUsage ($machineDNS)
            if( [int] $XAUsedMemory -lt 75) { "Memory usage is normal [ $XAUsedMemory % ]" | LogMe -display; $tests.MemUsg = "SUCCESS", "$XAUsedMemory %" }
		    elseif( [int] $XAUsedMemory -lt 85) { "Memory usage is medium [ $XAUsedMemory % ]" | LogMe -warning; $tests.MemUsg = "WARNING", "$XAUsedMemory %" }   	
		    elseif( [int] $XAUsedMemory -lt 95) { "Memory usage is high [ $XAUsedMemory % ]" | LogMe -error; $tests.MemUsg = "ERROR", "$XAUsedMemory %" }
		    elseif( [int] $XAUsedMemory -eq 101) { "Memory usage test failed" | LogMe -error; $tests.MemUsg = "ERROR", "Err" }
            else { "Memory usage is Critical [ $XAUsedMemory % ]" | LogMe -error; $tests.MemUsg = "ERROR", "$XAUsedMemory %" }   
		    $XAUsedMemory = 0  
            }
        else {
            $XAUsedMemory = 101 | LogMe -error; $tests.MemUsg = "ERROR", "WMI Err"
            }
`

`if ($WmiTest -eq $True) {
            foreach ($disk in $diskLettersWorkers)
            {
            # Check Disk Usage 
            $HardDisk = CheckHardDiskUsage -hostname $machineDNS -deviceID "$($disk):"
		    if ($HardDisk -ne $null) {	
			    $XAPercentageDS = $HardDisk.PercentageDS
			    $frSpace = $HardDisk.frSpace

			    If ( [int] $XAPercentageDS -gt 15) { "Disk Free is normal [ $XAPercentageDS % ]" | LogMe -display; $tests."$($disk)Freespace" = "SUCCESS", "$frSpace GB" } 
			    ElseIf ([int] $XAPercentageDS -eq 0) { "Disk Free test failed" | LogMe -error; $tests.CFreespace = "ERROR", "Err" }
			    ElseIf ([int] $XAPercentageDS -lt 5) { "Disk Free is Critical [ $XAPercentageDS % ]" | LogMe -error; $tests."$($disk)Freespace" = "ERROR", "$frSpace GB" } 
			    ElseIf ([int] $XAPercentageDS -lt 15) { "Disk Free is Low [ $XAPercentageDS % ]" | LogMe -warning; $tests."$($disk)Freespace" = "WARNING", "$frSpace GB" }     
			    Else { "Disk Free is Critical [ $XAPercentageDS % ]" | LogMe -error; $tests."$($disk)Freespace" = "ERROR", "$frSpace GB" }
			
			    $XAPercentageDS = 0
			    $frSpace = 0
			    $HardDisk = $null
    		    }
        
              }
            }
          else {
			  $XAPercentageDS = "N/A"
			  $frSpace = 0
			  $HardDisk = $null
            }```

So in the report itself it will display WMI Err if it could not do a WMI check

**Comment by mohanrajramaraj** [comment]
Error wmi connection failed-Check Wmi for corruption
Have anyone experience the issue,currently Iam facing this problem.any suggestion

**Comment by julianoabr** [comment]
Hi everyone, I am from Brazil. I am facing the same issue, when WMI test fails, another tests that depends of WMI fail too. The suggestion of @MikedaSpike  is the right way. When WMI fails it does not have to test cpu usage, memory usage or any other test that depends of WMI. @sacha81, please merge these correction suggested by @MikedaSpike in our main script. 
Thanks, regards

**Comment by julianoabr** [comment]
Follow the way that I solve the issue:

# Column Uptime (Query over WMI - only if Ping successfull)
    $tests.WMI = "ERROR","Error"
    
    $job = Start-Job -ScriptBlock $wmiOSBlock -ArgumentList $machineDNS
    
    $wmi = Wait-job $job -Timeout 10 | Receive-Job

# Perform WMI related checks
    if ($null -ne $wmi) {
	    
        $tests.WMI = "SUCCESS", "Success"
	    
        $LBTime=[Management.ManagementDateTimeConverter]::ToDateTime($wmi.Lastbootuptime)
	    
        [TimeSpan]$uptime=New-TimeSpan $LBTime $(get-date)

	    if ($uptime.days -gt $maxUpTimeDays) {
		
            "reboot warning, last reboot: {0:D}" -f $LBTime | LogMe -display -warning
		    $tests.Uptime = "WARNING", $uptime.days
	    }#end of if test uptime
        else {
		
            $tests.Uptime = "SUCCESS", $uptime.days
	    }#end of Else test uptime

        
#==============================================================================================
#               CHECK CPU AND MEMORY USAGE 
#==============================================================================================

        # Check the AvgCPU value for 5 seconds
        $XAAvgCPUval = CheckCpuUsage ($machineDNS)
		#$VDtests.LoadBalancingAlgorithm = "SUCCESS", "LB is set to BEST EFFORT"} 
			
        if( [int] $XAAvgCPUval -lt 75) { "CPU usage is normal [ $XAAvgCPUval % ]" | LogMe -display; $tests.AvgCPU = "SUCCESS", "$XAAvgCPUval %" }
		elseif([int] $XAAvgCPUval -lt 85) { "CPU usage is medium [ $XAAvgCPUval % ]" | LogMe -warning; $tests.AvgCPU = "WARNING", "$XAAvgCPUval %" }   	
		elseif([int] $XAAvgCPUval -lt 95) { "CPU usage is high [ $XAAvgCPUval % ]" | LogMe -error; $tests.AvgCPU = "ERROR", "$XAAvgCPUval %" }
		elseif([int] $XAAvgCPUval -eq 101) { "CPU usage test failed" | LogMe -error; $tests.AvgCPU = "ERROR", "Err" }
        else { "CPU usage is Critical [ $XAAvgCPUval % ]" | LogMe -error; $tests.AvgCPU = "ERROR", "$XAAvgCPUval %" }   
		$XAAvgCPUval = 0

        # Check the Physical Memory usage       
        [int] $XAUsedMemory = CheckMemoryUsage ($machineDNS)
        if( [int] $XAUsedMemory -lt 75) { "Memory usage is normal [ $XAUsedMemory % ]" | LogMe -display; $tests.MemUsg = "SUCCESS", "$XAUsedMemory %" }
		elseif( [int] $XAUsedMemory -lt 85) { "Memory usage is medium [ $XAUsedMemory % ]" | LogMe -warning; $tests.MemUsg = "WARNING", "$XAUsedMemory %" }   	
		elseif( [int] $XAUsedMemory -lt 95) { "Memory usage is high [ $XAUsedMemory % ]" | LogMe -error; $tests.MemUsg = "ERROR", "$XAUsedMemory %" }
		elseif( [int] $XAUsedMemory -eq 101) { "Memory usage test failed" | LogMe -error; $tests.MemUsg = "ERROR", "Err" }
        else { "Memory usage is Critical [ $XAUsedMemory % ]" | LogMe -error; $tests.MemUsg = "ERROR", "$XAUsedMemory %" }   
		$XAUsedMemory = 0  

        foreach ($disk in $diskLettersWorkers)
        {
            # Check Disk Usage 
            $HardDisk = CheckHardDiskUsage -hostname $machineDNS -deviceID "$($disk):"
		    
            if ($null -ne $HardDisk) {	
			    $XAPercentageDS = $HardDisk.PercentageDS
			    $frSpace = $HardDisk.frSpace

			    If ( [int] $XAPercentageDS -gt 15) { 
                    "Disk Free is normal [ $XAPercentageDS % ]" | LogMe -display; $tests."$($disk)Freespace" = "SUCCESS", "$frSpace GB" 
                } 
			    ElseIf ([int] $XAPercentageDS -eq 0) {
                     "Disk Free test failed" | LogMe -error; $tests.CFreespace = "ERROR", "Err" 
                }
			    ElseIf ([int] $XAPercentageDS -lt 5) {
                     "Disk Free is Critical [ $XAPercentageDS % ]" | LogMe -error; $tests."$($disk)Freespace" = "ERROR", "$frSpace GB"
                } 
			    ElseIf ([int] $XAPercentageDS -lt 15) { 
                    "Disk Free is Low [ $XAPercentageDS % ]" | LogMe -warning; $tests."$($disk)Freespace" = "WARNING", "$frSpace GB"
                 }     
			    Else {
                     "Disk Free is Critical [ $XAPercentageDS % ]" | LogMe -error; $tests."$($disk)Freespace" = "ERROR", "$frSpace GB"
                 }
			
			    $XAPercentageDS = 0
			    $frSpace = 0
			    $HardDisk = $null
		    }
		
        }

       
    }#end of Test Wmi
    else{
	
    "WMI connection failed - check WMI for corruption" | LogMe -display -error
    	
    stop-job $job

    $XAAvgCPUval = 101 | LogMe -error; $tests.AvgCPU = "ERROR", "Wmi Err"
    
    $XAUsedMemory = 101 | LogMe -error; $tests.MemUsg = "ERROR", "Wmi Err"
    
    foreach ($disk in $diskLettersWorkers){
        
        $XAPercentageDS = 0 | LogMe -error; $tests."$($disk)Freespace" = "ERROR", "Wmi Err"

        $XAPercentageDS = 0
		$frSpace = 0
		$HardDisk = $null
                
    }


}#Else of Test WMI

**Comment by sacha81** [comment]
thanks https://github.com/julianoabr
