### ISSUE TITLE
Avg CPU not getting fetched

### ISSUE THREAD

**Issue by dev3695** [sacha81/XA-and-XD-HealthCheck#69]
Error Message in log" check performance counter. os Srver2012 r2 and 2016

**Comment by sacha81** [comment]
What language is you OS? Is WMI working properly?

**Comment by dev3695** [comment]
En-US. And yes wmi is working fine. All details are getting fetched.

**Comment by sacha81** [comment]
Maybe a permission issue with the user under which context the script is running?

**Comment by dev3695** [comment]
I am running with administrator permission. But same results.. every thing
is working except average cpu for controller as well as vda

**Comment by sacha81** [comment]
try to run the single code line of the script to see whats the issue

**Comment by sacha81** [comment]
Please try Version: 1.3.9 - is fixed with it
