### ISSUE TITLE
Query of Unmanaged Virtual Desktop is not working

### ISSUE THREAD

**Issue by citrixguyblog** [sacha81/XA-and-XD-HealthCheck#73]
The check of ping, Uptime, Regstate and OSBuild is not working when you have a machine which is in an unmanaged power state.

Change Line 1002 in the PowerShell Script to:
if ($Powered -eq "On" -OR $Powered -eq "Unknown" -OR $Powered -eq "Unmanaged") {

**Comment by sacha81** [comment]
solved in V 1.4.2
