### ISSUE TITLE
DFreespace is on N/A

### ISSUE THREAD

**Issue by sacha81** [sacha81/XA-and-XD-HealthCheck#8]
DFreespace is on N/A even if exists

**Comment by sommerers** [comment]
This is caused by a typo in the code. 

The section called $tests.DFreespace = "NEUTRAL", "N/A" under CHeck CPU and Memory Usage

If you look at the code the $test is referencing CFreespace, if you change this to DFreespace this is resolved.

Before Modifying

$tests.DFreespace = "NEUTRAL", "N/A" 
		if ( $XAServerHaveD -eq "1" ) {
			# Check D Disk Usage 
	        $HardDiskd = CheckHardDiskUsage -hostname $machineDNS -deviceID "D:"
			if ($HardDiskd -ne $null) {			
				$XAPercentageDSd = $HardDiskd.PercentageDS
				$frSpaced = $HardDiskd.frSpace

				If ( [int] $XAPercentageDSd -gt 15) { "Disk Free is normal [ $XAPercentageDSd % ]" | LogMe -display; $tests.CFreespace = "SUCCESS", "$frSpaced GB" } 
				ElseIf ([int] $XAPercentageDSd -eq 0) { "Disk Free test failed" | LogMe -error; $tests.CFreespace = "ERROR", "Err" }
				ElseIf ([int] $XAPercentageDSd -lt 5) { "Disk Free is Critical [ $XAPercentageDSd % ]" | LogMe -error; $tests.CFreespace = "ERROR", "$frSpaced GB" } 
				ElseIf ([int] $XAPercentageDSd -lt 15) { "Disk Free is Low [ $XAPercentageDSd % ]" | LogMe -warning; $tests.CFreespace = "WARNING", "$frSpaced GB" }     
				Else { "Disk Free is Critical [ $XAPercentageDSd % ]" | LogMe -error; $tests.CFreespace = "ERROR", "$frSpaced GB" }  
				
				$XAPercentageDSd = 0
				$frSpaced = 0
				$HardDiskd = $null
			}
		}

After Modifying

		$tests.DFreespace = "NEUTRAL", "N/A" 
		if ( $XAServerHaveD -eq "1" ) {
			# Check D Disk Usage 
	        $HardDiskd = CheckHardDiskUsage -hostname $machineDNS -deviceID "D:"
			if ($HardDiskd -ne $null) {			
				$XAPercentageDSd = $HardDiskd.PercentageDS
				$frSpaced = $HardDiskd.frSpace

				If ( [int] $XAPercentageDSd -gt 15) { "Disk Free is normal [ $XAPercentageDSd % ]" | LogMe -display; $tests.DFreespace = "SUCCESS", "$frSpaced GB" } 
				ElseIf ([int] $XAPercentageDSd -eq 0) { "Disk Free test failed" | LogMe -error; $tests.DFreespace = "ERROR", "Err" }
				ElseIf ([int] $XAPercentageDSd -lt 5) { "Disk Free is Critical [ $XAPercentageDSd % ]" | LogMe -error; $tests.DFreespace = "ERROR", "$frSpaced GB" } 
				ElseIf ([int] $XAPercentageDSd -lt 15) { "Disk Free is Low [ $XAPercentageDSd % ]" | LogMe -warning; $tests.DFreespace = "WARNING", "$frSpaced GB" }     
				Else { "Disk Free is Critical [ $XAPercentageDSd % ]" | LogMe -error; $tests.DFreespace = "ERROR", "$frSpaced GB" }  
				
				$XAPercentageDSd = 0
				$frSpaced = 0
				$HardDiskd = $null
			}
		}

**Comment by sacha81** [comment]
closed from 1.2.4
