### ISSUE TITLE
The variable '$PvsWriteCache' cannot be retrieved

### ISSUE THREAD

**Issue by sacha81** [sacha81/XA-and-XD-HealthCheck#9]
The variable '$PvsWriteCache' cannot be retrieved because it has not been set. 
At C:\CustomPowerShell\XA-and-XD-HealthCheck.ps1:771 char:47 
+ $PvsWriteCacheUNC = Join-Path "\\$machineDNS" $PvsWriteCache 
+                                               ~~~~~~~~~~~~~~ 
    + CategoryInfo          : InvalidOperation: (PvsWriteCache:String) [], RuntimeException 
    + FullyQualifiedErrorId : VariableIsUndefined 
  
The variable '$PvsWriteCacheUNC' cannot be retrieved because it has not been set. 
At C:\CustomPowerShell\XA-and-XD-HealthCheck.ps1:772 char:30 
+ $CacheDiskexists = Test-Path $PvsWriteCacheUNC 
+                              ~~~~~~~~~~~~~~~~~ 
    + CategoryInfo          : InvalidOperation: (PvsWriteCacheUNC:String) [], RuntimeException 
    + FullyQualifiedErrorId : VariableIsUndefined 
  
The variable '$CacheDiskexists' cannot be retrieved because it has not been set. 
At C:\CustomPowerShell\XA-and-XD-HealthCheck.ps1:773 char:5 
+ if ($CacheDiskexists -eq $True) { 
+     ~~~~~~~~~~~~~~~~ 
    + CategoryInfo          : InvalidOperation: (CacheDiskexists:String) [], RuntimeException 
    + FullyQualifiedErrorId : VariableIsUndefined

**Comment by tyron** [comment]
I think this is closed on #13
